ENG-142: Fix 'Meet The Team' Component
HoseaCodes/Mune-UI pull request #21
Opened 2024-10-02 22:51 UTC by rfougy

2024-10-03 00:34 UTC, rfougy commented on src/constants/bios.ts
Majority changes (except for adding Ashley as team member and new images) due to prettier formatting.

2024-10-03 02:53 UTC, HoseaCodes commented on src/constants/bios.ts
You can remove any reference to Ashley.

2024-10-04 19:12 UTC, HoseaCodes requested changes

2024-10-04 19:12 UTC, HoseaCodes commented on src/assets/team-members/Ashley-Lewis.png
You can remove this image

2024-10-04 19:12 UTC, HoseaCodes commented on src/components/meet-the-team/ExpandedTeamCard.tsx
> +  const truncateAfterFirstSentence = (
Let’s move this into utilities functions

2024-10-04 21:11 UTC, rfougy commented on src/assets/team-members/Ashley-Lewis.png
Ok. This image is also include in the Contact page, for now I've replaced the image of Ashley with Dana. I'll let Caleb know of this change and see if he prefers a different member photo.

2024-10-04 23:15 UTC, HoseaCodes submitted a review, later dismissed

2024-10-08 02:02 UTC, HoseaCodes approved these changes

2024-10-08 02:04 UTC, merged